# Generated by Django 3.0.3 on 2020-03-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateField(verbose_name='date created')),
                ('timeCreated', models.TimeField(verbose_name='time created')),
                ('prodInfo', models.CharField(max_length=200)),
                ('buyingPartyInfo', models.CharField(max_length=200)),
                ('sellingPartyInfo', models.CharField(max_length=200)),
                ('notionalAmount', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('maturityDate', models.DateField(verbose_name='maturity date')),
                ('underlyingAmount', models.PositiveIntegerField()),
                ('underlyingCurrency', models.CharField(choices=[('GBP', 'Pounds'), ('USD', 'Dollars')], default='GBP', max_length=3)),
                ('strikePrice', models.PositiveIntegerField()),
            ],
        ),
    ]
