# Generated by Django 3.0.4 on 2020-03-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='currencyValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date created')),
                ('currency', models.CharField(choices=[('GBP', 'Pounds'), ('USD', 'Dollars')], default='GBP', max_length=3)),
                ('valueInUSD', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='notionalAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('buyer', models.CharField(max_length=200)),
                ('seller', models.CharField(max_length=200)),
                ('mean', models.FloatField()),
                ('standard_deviation', models.FloatField()),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
                ('count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='quantityEstimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('buyer', models.CharField(max_length=200)),
                ('seller', models.CharField(max_length=200)),
                ('mean', models.FloatField()),
                ('standard_deviation', models.FloatField()),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
                ('count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='stockPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date created')),
                ('companyID', models.CharField(max_length=200)),
                ('stockPrice', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='strikePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('buyer', models.CharField(max_length=200)),
                ('seller', models.CharField(max_length=200)),
                ('mean', models.FloatField()),
                ('standard_deviation', models.FloatField()),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
                ('count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateField(verbose_name='date created')),
                ('timeCreated', models.TimeField(verbose_name='time created')),
                ('prodInfo', models.CharField(max_length=200)),
                ('buyingPartyInfo', models.CharField(max_length=200)),
                ('sellingPartyInfo', models.CharField(max_length=200)),
                ('notionalAmount', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('maturityDate', models.DateField(verbose_name='maturity date')),
                ('underlyingAmount', models.PositiveIntegerField()),
                ('underlyingCurrency', models.CharField(choices=[('GBP', 'Pounds'), ('USD', 'Dollars')], default='GBP', max_length=3)),
                ('strikePrice', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='underlyingPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('buyer', models.CharField(max_length=200)),
                ('seller', models.CharField(max_length=200)),
                ('mean', models.FloatField()),
                ('standard_deviation', models.FloatField()),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
                ('count', models.PositiveIntegerField()),
            ],
        ),
    ]
