# Generated by Django 3.0.4 on 2020-03-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_auto_20200301_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='strikePrice',
            field=models.FloatField(),
        ),
    ]
