# Generated by Django 3.0.4 on 2020-03-06 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_auto_20200306_1304'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='currencyValues',
            new_name='currencyValue',
        ),
        migrations.RenameModel(
            old_name='stockPrices',
            new_name='stockPrice',
        ),
    ]
